### ISSUE TITLE
wrong link in DPCTF results page

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#16]
If you look this screen dump of a DPCTF results page, you will see the link to github.com is to WMAS2017 which is wrong. There may be other things wrong about it too.

![image](https://user-images.githubusercontent.com/8490792/129572361-35a21370-1596-4e02-aad7-8234b159729c.png)

**Comment by louaybassbouss** [comment]
Thanks @jpiesing we will check and fix it. The links should point to the tests in the [generated](https://github.com/cta-wave/dpctf-tests/tree/master/generated) folder.

**Comment by FritzHeiden** [comment]
This is fixed now. As this is part of the Dockerfile script, please recreate the docker image from scratch.

**Comment by louaybassbouss** [comment]
@jpiesing please check and close if the issue if fixed on your side.

**Comment by jpiesing** [comment]
> This is fixed now. As this is part of the Dockerfile script, please recreate the docker image from scratch.

Sorry but this isn't fixed. I believe I have recreated the docker image from scratch - docker-compose. Unless of course you mean actually deleting the docker image.

![image](https://user-images.githubusercontent.com/8490792/134672289-f6c1cbab-ad24-4505-b290-f3a4a6e41a2d.png)

**Comment by FritzHeiden** [comment]
Using the `./build.sh` script with `--reload-runner` isn't sufficient, as the tool that creates these reports is separate from the test runner and installed before the runner. So yes, you would need to delete the whole image to make sure the step of installing the wptreport tool is actually executed and not loaded from cache.

**Comment by jpiesing** [comment]
@FritzHeiden  To be clear, do you mean `docker rm dpctf` or something else?

**Comment by FritzHeiden** [comment]
`docker rmi dpctf`. To be sure, all dpctf related images have to be removed
